# Generated by Django 5.0.1 on 2024-07-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web'), ('DATA_SCIENCE', 'Data Science'), ('GAMES', 'Games')], default='WEB', max_length=20),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
