# Generated by Django 5.0.1 on 2024-07-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_projects_category_alter_projects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('WEB', 'Web'), ('DATA_SCIENCE', 'Data Science'), ('GAMES', 'Games'), ('RPA', 'Rpa')], default='RPA', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('WEB', 'Web'), ('DATA_SCIENCE', 'Data Science'), ('GAMES', 'Games'), ('RPA', 'Rpa')], default='WEB', max_length=20),
        ),
    ]
